Repository Clueless-Community/seamless-ui, pull requests merged in 2022-12, with the labels that each got.

#665 Update rating-2.html
  Rating/src/rating-2.html
Labels: CodePeak’22, EASY

#669 Made some changes and added new style stars in the rating1.html
  Rating/src/rating-1.html
Labels: CodePeak’22, EASY

#670 Avatar's height and width Fixed
  Avatar/src/avatar-text.html
Labels: CodePeak’22, EASY

#673 Fix height and width in avatar-status
  Avatar/src/avatar-status.html
Labels: CodePeak’22, EASY

#681 Updated Badge design system file
  Badges/badges.design-system.mdx
Labels: CodePeak’22, EASY

#704 logo text improved as per Navbar Design System
  Navbar/src/navbar-0.html
Labels: points:5, points:1, codepeak 22

#729 login button updated and nav tag fixed
  Navbar/src/navbar-07.html
Labels: points:5, codepeak 22

#736 Contact-4 made responsive and design updated
  Contact/src/contact-4.html
Labels: points:10, codepeak 22

#738 Team-Component
  Team/Readme.md
  Team/src/team-01.html
Labels: points:20, codepeak 22

#863 rating style guide updated
  Rating/rating.style-guide.mdx
Labels: points:10, codepeak 22

#906 Added footer-dark-16 and made it responsive
  Footer/src/footer-dark-16.html
Labels: points:5, codepeak 22

#905 Added footer-white-16 and made it responsive
  Footer/src/footer-white-16.html
Labels: points:5, codepeak 22

#897 Added footer-blue-16 and made it responsive
  Footer/src/footer-blue-16.html
Labels: points:5, codepeak 22

#949 Added content-card-9
  Content Cards/src/content-card-7.html
  Content Cards/src/content-card-9.html
Labels: points:5, codepeak 22

#991 Improved timeline-2
  Timeline/src/timeline-2.html
Labels: points:10, codepeak 22

#1047 Improved a better UI for stats-0.html
  Stats/src/stats-0.html
Labels: points:10, codepeak 22

#1087 Improved search-btn-with-category form
  Form groups/src/search-with-category-and-btn-vertical.html
Labels: points:10, codepeak 22

#1086 Improved search-with-button form
  Form groups/src/search-with-btn.html
Labels: points:10, codepeak 22

#1085 Improved search-with-category form
  Form groups/src/search-with-category-and-btn-horizontal.html
Labels: points:10, codepeak 22

#1084 Breadcrumb Readme Added
  Breadcrumb/README.md
  Breadcrumb/breadcrum.design-system.mdx
Labels: points:5, codepeak 22

#1104 Create radio-button.html
  Form/src/radio-button.html
Labels: points:5, codepeak 22

#1106 Create checkbox.html
  Form/src/checkbox.html
Labels: points:5, codepeak 22

#1103 Create radio-colored.html
  Form/src/radio-colored.html
Labels: points:5, codepeak 22

#1107 Create dropzone.html
  Form/src/dropzone.html
Labels: points:10, codepeak 22

#1133 Created readme for Form groups
  Form groups/README.md
Labels: points:10, codepeak 22

#1179 Added Navbar mobile nav-8
  Navbar/src/Nav-mobile/nav-8.html
Labels: points:10, codepeak 22

#1173 Improved Navbar nav-4 and made it responsive
  Navbar/src/Nav-mobile/nav-4.html
Labels: points:10, codepeak 22

#1169 Improved Navbar mobile nav-3
  Navbar/src/Nav-mobile/nav-3.html
Labels: points:10, codepeak 22

#1217 Created a readme for dropdown
  Dropdown/README.md
Labels: points:10, codepeak 22

#1218 footer White 18 Improved
  Footer/src/footer-white-18.html
Labels: points:10, codepeak 22

#1216 Created a readme for stats
  Stats/README.md
Labels: points:10, codepeak 22

#1224 Created a readme for rating
  Rating/README.md
  Rating/src/rating-3-dark.html
  Rating/src/rating-4-dark.html
Labels: points:10, codepeak 22

#1262 Improved footer-dark-3
  Footer/src/footer-dark-03.html
Labels: points:10, codepeak 22

#1261 Improved footer-blue-14
  Footer/src/footer-blue-14.html
Labels: points:10, codepeak 22

#1266 Improved Footer Dark 17
  Footer/src/footer-blue-17.html
  Footer/src/footer-dark-17.html
  Footer/src/footer-white-17.html
  Inputs/src/email.html
  Inputs/src/textarea.html
Labels: points:10, codepeak 22

#1263 Improved footer-white-14
  Footer/src/footer-white-14.html
Labels: points:10, codepeak 22

#1253 created readme for Team
  Team/Readme.md
  Timeline/src/readme.md
Labels: points:10, codepeak 22

#1269 Created a readme for filters
  Filters/README.md
  Filters/src/mobile/marketplace-1.html
  Filters/src/mobile/marketplace-product-1.html
Labels: points:10, codepeak 22

#1286 Update content card readme.md
  Content Cards/README.md
Labels: points:10, codepeak 22

#1287 Update testimonial-9.html
  Testimonials/src/testimonial-9.html
Labels: points:10, codepeak 22

#1288 Update testimonial-1.html
  Testimonials/src/testimonial-1.html
Labels: points:10, codepeak 22

#1289 created readme for Inputs
  Inputs/README.md
Labels: points:10, codepeak 22

#1290 Update stats-0.html
  Stats/src/stats-0.html
Labels: points:10, codepeak 22

#1291 Update stats-1.html
  Stats/src/stats-1.html
Labels: points:10, codepeak 22

#1292 updated readme.md for others
  Others/readme.md
Labels: points:10, codepeak 22

#1298 Update feedback-1.html
  Feedback Form/src/feedback-1.html
Labels: points:10, codepeak 22

#1299 Update movie-card-2.html
  Movie Card/src/movie-card-2.html
Labels: points:10, codepeak 22

#1301 Update Readme.md
  Movie Card/Readme.md
Labels: points:10, codepeak 22

#1307 create readme.md file of feedback form
  Feedback Form/readme.md
Labels: points:10, codepeak 22

#1315 Text color changes on hover
  Buttons/src/social-buttons.html
Labels: points:10, codepeak 22

#1306 Delete Feedback_Form directory
  Feedback_Form/readme.md
Labels: points:5, codepeak 22

#1308 Delete Content_Cards directory
  Content_Cards/README.md
Labels: points:5, codepeak 22

#1309 Delete Movie_Card directory
  Movie_Card/Readme.md
Labels: points:5, codepeak 22

#1300 Added the dark mode feature
  Timeline/src/timeline-1.html
  Timeline/src/timeline-2.html
Labels: points:10, codepeak 22

#1371 Improved footer dark 16
  Footer/src/footer-dark-16.html
Labels: points:5, codepeak 22

#1394 Improved Footer Dark 1
  Footer/src/footer-dark-01.html
  Footer/src/footer-dark-02.html
Labels: points:5, codepeak 22

#1390 Update README.md for Testimonials
  Testimonials/README.md
Labels: points:5, codepeak 22

#1391 Updated readme.md for Feedback forms
  Feedback Form/readme.md
Labels: points:5, codepeak 22

#1392 Updated Readme.md for Movie_card
  Movie Card/Readme.md
Labels: points:5, codepeak 22

#1414 Improved Footer White 1
  Footer/src/footer-white-0.html
  Footer/src/footer-white-01.html
Labels: points:5, codepeak 22

#1398 Update store-button-amazon-lightmode.html
  Store Buttons/src/store-button-amazon-lightmode.html
Labels: points:5, codepeak 22

#1399 Update store-button-apple-darkmode.html
  Store Buttons/src/store-button-apple-darkmode.html
Labels: points:5, codepeak 22

#1400 Update store-button-apple-lightmode.html
  Store Buttons/src/store-button-apple-lightmode.html
Labels: points:5, codepeak 22

#1401 Update store-button-google-play-darkmode.html
  Store Buttons/src/store-button-google-play-darkmode.html
Labels: points:5, codepeak 22

#1402 Update store-button-google-play-lightmode.html
  Store Buttons/src/store-button-google-play-lightmode.html
Labels: points:5, codepeak 22

#1403 Update store-button-windows-darkmode.html
  Store Buttons/src/store-button-windows-darkmode.html
Labels: points:5, codepeak 22

#1404 Update store-button-windows-lightmode.html
  Store Buttons/src/store-button-windows-lightmode.html
Labels: points:5, codepeak 22

#1405 Update README.md
  Store Buttons/README.md
Labels: points:5, codepeak 22

#1406 Delete Store_Buttons directory
  Store_Buttons/README.md
Labels: points:5, codepeak 22

#1441 Delete readme.md
  Timeline/src/readme.md
Labels: points:5, codepeak 22

#1442 Create readme.md
  Timeline/readme.md
Labels: points:5, codepeak 22

#1444 Improved footer blue 14
  Footer/src/footer-blue-14.html
Labels: points:5, codepeak 22

#1465 design system.mdx for store buttons
  Store_Buttons/store-buttons.design-system.mdx
Labels: points:10, codepeak 22

#1474 design system for widgets
  Widgets/widgets.design-system.mdx
Labels: points:10, codepeak 22
