Repository Clueless-Community/seamless-ui, pull requests merged in 2023-03, with the labels that each got.

#1982 Added amazon store button blue
  Store Buttons/src/store-button-amazon-blue.html
Labels: EASY, JWOC

#1983 Main
  Store Buttons/src/store-button-amazon-white.html
Labels: EASY, JWOC

#1972 Created Pricing card 5 white
  Pricing Components/src/pricing-card-5-white.html
Labels: EASY, WOC

#1973 Created pricing card 5 blue
  Pricing Components/src/pricing-card-5-blue.html
Labels: WOC

#1974 Created pricing card 5 black
  Pricing Components/src/pricing-card-5-black.html
Labels: WOC

#1985 Created product card 4 white
  Product Cards/src/product-card-4-white.html
Labels: WOC

#2011 Created store button windows black
  Store Buttons/src/store-button-windows-black.html
Labels: EASY, JWOC

#2014 Added google play button blue
  Store Buttons/src/store-button-google-play-blue.html
Labels: EASY, JWOC

#2013 google-play black logo
  Store Buttons/src/store-button-google-play-black.html
Labels: EASY, JWOC

#1975 store-button-windows-white
  Store Buttons/src/store-button-windows-white.html
Labels: EASY, JWOC

#2018 Create store-button-amazon-black.html
  Store Buttons/src/store-button-amazon-black.html
Labels: EASY, JWOC

#2015 Created Store Button apple black
  Store Buttons/src/store-button-apple-black.html
  Store Buttons/src/store-button-apple-darkmode.html
Labels: WOC

#2026 #2009 create select round white
  Form/src/select-rounded-white.html
Labels: EASY, JWOC

#2021 Created search rounded white
  Form/src/search-rounded-white.html
Labels: WOC

#2035 Create Google play button white #1977, Solved
  Store Buttons/src/store-button-google-play-white.html
Labels: EASY, JWOC

#2034 Created search rounded black
  Form/src/search-rounded-black.html
Labels: WOC

#2027 Form/src/message-textarea-black.html file added
  Form/src/message-textarea-black.html
Labels: EASY, JWOC

#2036 text color changed
  Form/src/email-rounded-black.html
Labels: EASY, JWOC

#2037 made radio button white
  Form/src/radio-button-white.html
Labels: EASY, JWOC

#2030 store button apple white
  Store Buttons/src/store-button-apple-white.html
Labels: EASY, JWOC

#2043 Created textarea white
  Form/src/message-textarea-white.html
Labels: EASY, JWOC

#2045 Made text area white file
  Form/src/message-textarea-white.html
Labels: EASY, JWOC

#2048 Update radio black
  Form/src/radio-button-black.html
Labels: EASY, JWOC

#2041 added radio-button-black file
  Form/src/radio-button-black.html
Labels: EASY, JWOC

#2049 email-rounded-white
  Form/src/email-rounded-white.html
Labels: EASY, JWOC

#2038 Create choose-file-rounded-black.html
  choose-file-rounded-black.html
Labels: EASY, JWOC

#2039 Created message textarea rounded black
  Form/src/message-textarea-rounded-black.html
Labels: EASY, JWOC

#2052 #2010 create selected rounded black
  Form/src/select-rounded-black.html
Labels: EASY, JWOC

#2056 Update Readme.md
  README.md
Labels: EASY, JWOC

#2059 #2008 created select-black
  Form/src/select-black.html
Labels: EASY, JWOC

#2044 Create Select White #2007
  Form/src/select-white.html
Labels: EASY, JWOC

#2060 Accordion-3 updated
  Accordion/README.md
  Accordion/accordion.design-system.mdx
  Accordion/src/accordion-3.html
Labels: EASY, JWOC

#2065 added product-card-3-white file
  Product Cards/src/Product-card-3-white.html
Labels: EASY, JWOC

#2055 Create checkbox Black #1988, Solved
  Form/src/checkbox-buttons-black.html
Labels: MEDIUM, JWOC

#2084 Updated Avatars Readme
  Avatar/README.md
Labels: WOC

#2083 Updated Alerts Readme
  Alerts/README.md
Labels: WOC

#2082 Added content card 13 blue
  Content Cards/src/content-card-13-blue.html
Labels: EASY, JWOC

#2081 Update Pricing Card Readme
  Pricing Components/README.md
Labels: HARD, JWOC

#2080 Product card Readme updated
  Product Cards/README.md
Labels: HARD, JWOC

#2077 Badges added
  README.md
Labels: MEDIUM, JWOC

#2076 improved breadcrumb
  Breadcrumb/src/Breadcrumb.html
  Breadcrumb/src/Breadcumb.html
Labels: HARD, JWOC

#2086 Image link is replaced in testimonial-1-blue
  Testimonials/src/testimonial-1-blue.html
Labels: EASY, JWOC

#2088 Updated badges Readme
  Badges/README.md
Labels: MEDIUM, WOC

#2090 improved breadcrumb 3
  Breadcrumb/src/breadcrumb-3.html
Labels: HARD, JWOC

#2093 Updated Avatar-group.html
  Avatar/src/avatar-group.html
Labels: EASY, WOC

#2094 Image is replaced in testimonial-black-1
  Testimonials/src/testimonial-1-black.html
Labels: EASY, JWOC
